# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_ZTE_ZX279133_BOOTINFO) += zx279133-bootinfo.o
obj-$(CONFIG_ZTE_ZX279133_PWM_AUDIT) += zx279133-pwm-audit.o
obj-$(CONFIG_ZTE_ZX279133_XPCS_NPPT_AUDIT) += zx279133-xpcs-nppt-audit.o
